### ISSUE TITLE
Feature request - display 'favorite' icon next to games selected as favorites

### ISSUE THREAD

**Issue by iwubcode** [mmatyas/pegasus-theme-grid#4]
The 'gameos' theme shows a little icon next to games that are your favorite, it'd be nice to have something similar to the default theme

**Comment by iwubcode** [comment]
@mmatyas - not trying to rush you but wanted to make sure you were aware I opened issues/features here.  Would main project 'pegasus-frontend' have been a better location?  I can close these and open them there instead if it's better.

**Comment by mmatyas** [comment]
No it's perfectly fine here, I just haven't had the time to deal with all the theme related things across the repos yet (wanting to do too many things at once!). I do am aware of them though; most of them like this aren't difficult to make, I just need to sit down and write theme code one of these days.

**Comment by iwubcode** [comment]
Ah no worries at all.  I know all too well how it is when have lots of tasks to do at one time.  Thanks for letting me know and thank you for pegasus, it's a great front-end!

**Comment by mmatyas** [comment]
Ok, took some time but there's now a little :heart: next to the favorite games.
