### ISSUE TITLE
Logo requests

### ISSUE THREAD

**Issue by TiZ-HugLife** [mmatyas/pegasus-theme-grid#7]
Hi there. The logo coverage is pretty good, but I'd like to request a few additional ones:

MS-DOS, Windows 3.1, Windows, Linux (so Tux basically)
An alternative PC logo that combines the Windows logo and the Linux logo
Gen-6 consoles: GameCube, Wii, Playstation 2, XBox
Gen-7 consoles: Wii U, Playstation 3, XBox 360

I don't think we have access to good emulation for xbox or 360 yet, but I don't think it'd hurt to have the logos ready.

Where are the current logos sourced from? I could give a whack to making them myself and then doing a pull request.

**Comment by mmatyas** [comment]
If I remember correctly, some of them might be from https://github.com/RetroPie/es-theme-simple, though that seems to have logos for more modern platforms. There have been a few additions by me as well, usually from the official source then touched up to match the rest. Feel free to send pull requests if you'd like to add some more!

**Comment by mmatyas** [comment]
OK, all requested logos are now available in the latest version. The only missing thing is the combined Win+Linux logo, but I'm not sure if it's even a valid category in the first place. Feel free to open a new issue if you have some ideas for improvement!

**Comment by TiZ-HugLife** [comment]
They look great, thank you very much!
