### ISSUE TITLE
Mismatch shortname for Gamecube

### ISSUE THREAD

**Issue by ellinge** [mmatyas/pegasus-theme-grid#8]
The switchOS-theme expects **gc** as shortname to show the Gamecube-asset logo.

In pegasus-theme-grid **ngc** is expected as shortname:
https://github.com/mmatyas/pegasus-theme-grid/blob/master/assets/logos/ngc.svg

For GameCube the Configuration generator sets **gc** as shortname
https://pegasus-frontend.org/tools/metagen-android/

I'm thinking the theme should match the generator, or at least add a gc.svg also.

**Comment by mmatyas** [comment]
Ok, this should be now fixed in the latest version, the grid theme now accepts both short names. Thanks for reporting the issue!
